// <auto-generated />
using System;
using Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Test")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ChildModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentModelId");

                    b.ToTable("Children", "Test");
                });

            modelBuilder.Entity("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ParentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Parents", "Test");
                });

            modelBuilder.Entity("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ChildModel", b =>
                {
                    b.HasOne("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ParentModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ParentModel", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentModelId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Boxit.BulkInsert.SQLServer.Test.Unit.EntityFramework.Models.ParentModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
